services:
  adguardhome:
    image: adguard/adguardhome:latest
    restart: always
    container_name: adguardhome
    ports:
      - 153:53/tcp
      - 153:53/udp
      - 3000:3000/tcp
    volumes:
      - /root/docker/adguardhome/workdir:/opt/adguardhome/work
      - /root/docker/adguardhome/confdir:/opt/adguardhome/conf
