services:
  dailyhot:
    image: rehiy/dailyhot
    ports:
      - "6688:80"
    restart: always
    environment:
      APP_ICP: "湘备20130401"
      APP_COPYRIGHT: "Example"
      APP_COPYRIGHT_URL: "http://www.example.org"
