services:
  xunlei:
    image: cnk3x/xunlei
    container_name: xunlei
    restart: always
    privileged: true
    network_mode: host
  # environment:     # 设置环境变量
  #   -
    volumes:
      - ./xunlei/data:/xunlei/data
      - /mnt/xl:/xunlei/downloads
