services:
  lookbusy:
    container_name: lookbusy
    image: fogforest/lookbusy
    restart: always
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
      - CPU_UTIL=10-20       # CPU占用（单位%），支持范围值
      - MEM_UTIL=15          # 内存占用（单位%）
      - SPEEDTEST_INTERVAL=600 # 网络测速间隔（分钟）
