docker run -itd --name=lookbusy --restart=always \
   -e TZ=Asia/Shanghai \
   -e CPU_UTIL=10-20 \ # CPU占用，单位%，不可省略，支持固定值或范围
   -e MEM_UTIL=15 \ # 内存占用，单位%，不跑内存可省略
   -e SPEEDTEST_INTERVAL=120 \ # 网络测速间隔，单位分钟，不跑网络可省略
   fogforest/lookbusy
